[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "project-auditor-pro"
version = "0.1.0"
authors = [
  { name = "devSunni", email = "yang@example.com" },
]
description = "Universal Project Architecture Auditor and Refactoring Guide"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
auditor = "auditor:main"

[tool.setuptools]
py-modules = ["auditor"]
